<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>PrintMeter.App.ViewModels</RootNamespace>
    <AssemblyName>PrintMeter.App.ViewModels</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrintMeter.Core\PrintMeter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.0.2" />
  </ItemGroup>
</Project>
