<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PrintMeter.Export</RootNamespace>
    <AssemblyName>PrintMeter.Export</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrintMeter.Core\PrintMeter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.3" />
    <PackageReference Include="CsvHelper" Version="33.0.1" />
  </ItemGroup>
</Project>
