<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PrintMeter.Pdf</RootNamespace>
    <AssemblyName>PrintMeter.Pdf</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrintMeter.Core\PrintMeter.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="PdfPig" Version="0.1.8" />
  </ItemGroup>
</Project>
