name: ci

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    env:
      DOTNET_MULTILEVEL_LOOKUP: "0"
      MSBuildEnableWorkloadResolver: false
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/*.props
            **/*.targets
            PrintMeter.sln

      - name: Restore
        run: dotnet restore PrintMeter.sln --nologo

      - uses: microsoft/setup-msbuild@v2

      - name: Build
        shell: pwsh
        run: |
          msbuild src/PrintMeter.App/PrintMeter.App.csproj `
            /t:Build `
            /p:Configuration=Release `
            /p:Platform=x64 `
            /p:Restore=false `
            /m `
            /v:m

      - name: Test
        run: dotnet test PrintMeter.Mac.slnf -c Release --no-restore --nologo

